name: AetherBall
version: ${version}
main: io.github.divinerealms.aetherball.AetherBall
authors:
  - neonsh
description: Soccer in Minecraft
depend: [ Vault, LuckPerms, TAB ]
softdepend: [ PlaceholderAPI ]